exports.jokes = [
    "Certaines personnes portent un pyjama Superman. Superman porte un pyjama Chuck Norris.",
    "Chuck Norris ne se mouille pas, c'est l'eau qui se Chuck Norris.",
    "Jesus Christ est né en 1940 avant Chuck Norris.",
    "Quand Google ne trouve pas quelque chose, il demande à Chuck Norris.",
    "Quand Chuck Norris utilise Windows, il ne plante pas.",
    "Chuck Norris peut écouter un CD complet de Diam's. Ça marche aussi avec Tragédie.",
    "C´est lorsque Mickael Jackson a croisé Chuck Norris qu'il est devenu blanc.",
    "Chuck Norris peut supprimer la corbeille.",
    "Chuck Norris reçoit des spams lui proposant de réduire la taille de son sexe.",
    "Chuck Norris ne vit pas sur Terre, la Terre vit sous Chuck Norris.",
    "Quand un moustique pique Chuck Norris, c'est le moustique qui se gratte.",
    "Chuck Norris peut diviser par zéro.",
    "Chuck Norris a déjà compté jusqu'à l'infini. Deux fois.",
    "Chuck Norris sait coder en binaire avec que des 0.",
    "Chuck Norris peut taguer le mur du son.",
    "Si Chuck Norris attaque l'Empire, l'Empire ne contre attaque pas.",
    "Chuck Norris nettoie Mr Propre.",
    "Google, c'est le seul endroit où tu peux taper Chuck Norris...",
    "Chuck Norris est contre les radars automatiques : ça l'éblouit lorsqu'il fait du vélo.",
    "Chuck Norris n'utilise pas de suppositoire. Les voies du seigneur sont impénétrables.",
    "Chuck Norris mange les emballages des carambars. On ne blague pas avec Chuck Norris.",
    "Chuck Norris peut remonter le terrain de foot dans Olive et Tom en moins d'un épisode.",
    "Chuck Norris a fini Super Mario Bros sans sauter.",
    "Chuck Norris est capable de laisser un message avant le bip sonore.",
    "Maitre Yoda a perdu la vie le jour où il a appelé Chuck Norris \"Norris Chuck\".",
    "Chuck Norris a fini son forfait illimité.",
    "Un film de Bruce Lee montre Chuck Norris se faire battre par Bruce Lee. C'est là l'effet spécial le plus cher de toute l'histoire du cinéma.",
    "Chuck Norris a fini Pokemon sans AUCUN pokemon. Chuck Norris n'a besoin de personne.",
    "Chuck Norris peut monter en bas.",
    "Un jour, les Power Rangers ont rencontré Chuck Norris. Maintenant on les appelle les Télétubbies.",
    "Quand la tartine de Chuck Norris tombe, la confiture change de côté.",
    "Chuck Norris n'a jamais gagné au Millionnaire, la roue tourne toujours...",
    "Chuck Norris a fini Super Mario Bros en 2 secondes, Bowser est venu s'excuser et lui a rendu la princesse, il est mort quand même...",
    "Quand Chuck Norris joue au Scrabble, l'Académie Française prend des notes.",
    "Chuck Norris peut te faire passer un sale quart d'heure en 8 minutes.",
    "Chuck Norris n'est jamais né. Il était là avant.",
    "Chuck Norris coupe des tranches de saucisson tellement fines qu'elles n'ont qu'une face.",
    "Chuck Norris n'apprend pas les dialogues de Walker Texas Ranger : il parle, et le metteur en scène adapte l'épisode.",
    "Pas la peine de dire ton nom à Chuck Norris, c'est lui qui décide comment tu t'appelles.",
    "Superman peut voler. Chuck Norris peut le faire atterir.",
    "On n'a pas donné la vie à Chuck Norris, c'est lui qui l'a prise.",
    "Chuck Norris : 99% de muscles, 99% d'intelligence.",
    "Quand il était jeune, Chuck Norris était bucheron dans la forêt du Sahara.",
    "Comme Lucky Luke, Chuck Norris tire plus vite que son ombre. Mais l'ombre de Chuck Norris tire plus vite que Lucky Luke.",
    "Quand Chuck Norris s’est mis au judo, David Douillet s’est mis aux pièces jaunes.",
    "Quand Chuck Norris rencontre un chêne, il l’abat, Chuck Norris n’aime pas les glands.",
    "Chuck Norris ne parle jamais au sens figuré : quand il dit \"je vais te faire manger la table\", vos doutes s'envolent.",
    "Donald a cette voix depuis que Chuck Norris l'a aidé à mettre sa cravate.",
    "Chuck Norris est connecté à l'ADSL depuis 1857.",
    "C'est Chuck Norris qui demande à Jean Pierre Foucault si c'est son dernier mot.",
    "Jesus avait donné un pain a Chuck Norris ... on l'a retrouvé cloué à un poteau.",
    "Lorsqu'une mouche se pose sur l'écran d'ordinateur de Chuck Norris, il clique dessus et la mouche meurt écrasée.",
    "Avec Chuck, Rien ne sert de partir à point, il faut courir !!",
    "Nobody is perfect. Nobody est un des surnoms de Chuck Norris.",
    "Chuck Norris peut tromper 1000 fois 1000 personnes.",
    "Chuck Norris peut travailler moins pour gagner plus.",
    "Meme les plus gros 4x4 n'ont pas de pare-chuck.",
    "Quand Chuck Norris pisse face au vent, le vent change de direction.",
    "Chuck Norris se prend parfois pour Dieu, tout le monde peut avoir un coup de déprime...",
    "Einstein disait : Il n'y a que deux choses infinies : l'univers, et la puissance de Chuck Norris, mais pour l'univers, je ne suis pas sur.",
    "Seul Chuck Norris a réussi à tracer une droite jusqu'a la fin"
]